### ISSUE TITLE
bbox have negative value 

### ISSUE THREAD

**Issue by zetwhite** [Adel-es/covid19_cctv_analyzer#7]
testVideo2.mp4로 테스트 하고 있는데, 263번 째 프레임에서 TID 6번인 사람의 bbox[0]이 음수값이 나옵니다!

제가 찍어서 확인한 로그는 아래와 같습니다. 
```
<= bbox of frameID_263 and TID_6
[ -1.63197922 396.23780562 169.61721093 893.06900656]
```

영상에서는 아래와 같은 상황에서 음수값을 가지게 되는 것 같습니다. 

![image](https://user-images.githubusercontent.com/61981457/127974681-ddac984a-95ce-46c4-a4a0-0e4e934bb95d.png)

**Comment by fridaySong3** [comment]
bounding box 좌표가 frame에서 벗어나지 않도록 수정하여 main으로 commit (3d4b96d)하였습니다.
